services:
  - type: web
    name: la-rail-live-map
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: METROLINK_API_KEY
        sync: false
